# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='authors',
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.AuthorInfo'),
        ),
    ]
